### ISSUE TITLE
covid mcmc example

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#132]
in covid_mcmc tutorial the SPDE gets the best fit statistics but it is never explained why. Should we provide some interpretation and reasoning as to why? I suggest something about how the SPDE captures the spatial wavelenngth that other methods don't. but i dont know why the mcmc method wouldn't unless it doesnt have enough iterations.

**Comment by XueqingYin** [comment]
The reasons are complex, and it’s hard to provide a definitive explanation. INLA-SPDE doesn't necessarily beat MCMC, they are just two different inference methods. INLA is faster, and previous simulations have shown similar inference results to MCMC.

What you suggested could be one possible reason. In this particular ‘covid_mcmc tutorial’, I think the different performance between INLA-SPDE and MCMC is because of the different spatio-temporal models being used. In MCMC, I used the BYM model, where the spatial correlation structure is captured by a N*N adjacency matrix (N is the number of spatial points). Basically, if two locations are adjacent in geography, they are spatially correlated, leading to data smoothing. However, the INLA-SPDE approach uses the Matern model, where spatial correlation depends on the distance between two locations rather than their geographic adjacency. In other words, even if two locations are not geographically adjacent, they can still be correlated. INLA-SPDE doesn't always outperform MCMC. Both model choice and data characteristics could impact the modelling performance.

Xueqing

**Comment by mnky9800n** [comment]
Oh thats a good point. I think what can fix this issue then is explaining the choice of MCMC, INLA-SPDE, and BYM. basically like you do here. Because currently its not in the tutorial.
