### ISSUE TITLE
Enforce limits on mesh size in mesh builder

### ISSUE THREAD

**Issue by gareth-j** [4DModeller/fdmr#43]
Should we enforce the following as is done in the `INLA::mesh_builder tool`? These are passed to the meshing function.

```
max.n=c(48000, 16000), ## Safeguard against large meshes.
max.n.strict=c(128000, 128000), ## Don't build a huge mesh!
```

**Comment by XueqingYin** [comment]
Hi Gareth,

I think we could keep max.n, and set its default value as -1 as done in inla.mesh.2d(). According to the R help documentation ?INLA::inla.mesh.2d(max.n=...), the 'max.n' parameter controls the maximum number of vertices allowed, overriding max.edge only.  inla.mesh.2d() only sets its default value as -1, which means no limit. But if users wish to impose a specific limit on the maximum vertices number, they can also pass corresponding values to the function.                                                                                                           

The help document explains that 'max.n.strict' controls the maximum number of vertices allowed, overriding both the 'min.angle' and 'max.edge' parameters. The default value is -1, meaning no limit.  Since we haven't incorporated the 'min.angle' parameter in the mesh builder tool yet, I suggest omitting 'max.n.strict' for now. We can consider its inclusion in the future if we decide to incorporate the 'min.angle' parameter into the tool.


Xueqing

**Comment by gareth-j** [comment]
Closing as we won't look into passing these parameters.
